modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
authors="gigaherz" #optional
license="BSD (3 clause)"


[[mods]]
    modId="dumpmodel"
    version="${file.jarVersion}"
    displayName="Example Mod"

[[dependencies.dumpmodel]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dumpmodel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"
