modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
authors="gigaherz" #optional
license="BSD (3 clause)"


[[mods]]
    modId="dumpmodel"
    version="${file.jarVersion}"
    displayName="Example Mod"

[[dependencies.dumpmodel]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dumpmodel]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.0,)"
    ordering="NONE"
    side="BOTH"
